-- Load one RAND HRS health observation per respondent and wave.
-- Run after the cohort, wave, and respondent loads.
-- UNPIVOT INCLUDE NULLS preserves each source respondent-wave observation;
-- no RAND special values are recoded because no missing-code mapping was specified.
WITH source_base AS
(
    SELECT HHIDPN,
        R1SHLT,
        R1BMI,
        R1HIBPE,
        R1DIABE,
        R1CANCRE,
        R1LUNGE,
        R1HEARTE,
        R1STROKE,
        R1PSYCHE,
        R1ARTHRE,
        R2SHLT,
        R2BMI,
        R2HIBPE,
        R2DIABE,
        R2CANCRE,
        R2LUNGE,
        R2HEARTE,
        R2STROKE,
        R2PSYCHE,
        R2ARTHRE,
        R3SHLT,
        R3BMI,
        R3HIBPE,
        R3DIABE,
        R3CANCRE,
        R3LUNGE,
        R3HEARTE,
        R3STROKE,
        R3PSYCHE,
        R3ARTHRE,
        R4SHLT,
        R4BMI,
        R4HIBPE,
        R4DIABE,
        R4CANCRE,
        R4LUNGE,
        R4HEARTE,
        R4STROKE,
        R4PSYCHE,
        R4ARTHRE,
        R5SHLT,
        R5BMI,
        R5HIBPE,
        R5DIABE,
        R5CANCRE,
        R5LUNGE,
        R5HEARTE,
        R5STROKE,
        R5PSYCHE,
        R5ARTHRE,
        R6SHLT,
        R6BMI,
        R6HIBPE,
        R6DIABE,
        R6CANCRE,
        R6LUNGE,
        R6HEARTE,
        R6STROKE,
        R6PSYCHE,
        R6ARTHRE,
        R7SHLT,
        R7BMI,
        R7HIBPE,
        R7DIABE,
        R7CANCRE,
        R7LUNGE,
        R7HEARTE,
        R7STROKE,
        R7PSYCHE,
        R7ARTHRE,
        R8SHLT,
        R8BMI,
        R8HIBPE,
        R8DIABE,
        R8CANCRE,
        R8LUNGE,
        R8HEARTE,
        R8STROKE,
        R8PSYCHE,
        R8ARTHRE,
        R9SHLT,
        R9BMI,
        R9HIBPE,
        R9DIABE,
        R9CANCRE,
        R9LUNGE,
        R9HEARTE,
        R9STROKE,
        R9PSYCHE,
        R9ARTHRE,
        R10SHLT,
        R10BMI,
        R10HIBPE,
        R10DIABE,
        R10CANCRE,
        R10LUNGE,
        R10HEARTE,
        R10STROKE,
        R10PSYCHE,
        R10ARTHRE,
        R11SHLT,
        R11BMI,
        R11HIBPE,
        R11DIABE,
        R11CANCRE,
        R11LUNGE,
        R11HEARTE,
        R11STROKE,
        R11PSYCHE,
        R11ARTHRE,
        R12SHLT,
        R12BMI,
        R12HIBPE,
        R12DIABE,
        R12CANCRE,
        R12LUNGE,
        R12HEARTE,
        R12STROKE,
        R12PSYCHE,
        R12ARTHRE,
        R13SHLT,
        R13BMI,
        R13HIBPE,
        R13DIABE,
        R13CANCRE,
        R13LUNGE,
        R13HEARTE,
        R13STROKE,
        R13PSYCHE,
        R13ARTHRE,
        R14SHLT,
        R14BMI,
        R14HIBPE,
        R14DIABE,
        R14CANCRE,
        R14LUNGE,
        R14HEARTE,
        R14STROKE,
        R14PSYCHE,
        R14ARTHRE,
        R15SHLT,
        R15BMI,
        R15HIBPE,
        R15DIABE,
        R15CANCRE,
        R15LUNGE,
        R15HEARTE,
        R15STROKE,
        R15PSYCHE,
        R15ARTHRE,
        R16SHLT,
        R16BMI,
        R16HIBPE,
        R16DIABE,
        R16CANCRE,
        R16LUNGE,
        R16HEARTE,
        R16STROKE,
        R16PSYCHE,
        R16ARTHRE
    FROM dev_catalog.brz_raw_hrs.randhrs1992_2022v1
),
wave_observations AS
(
    SELECT HHIDPN,
        wave_number,
        shlt, bmi, hibpe, diabe, cancre, lunge, hearte, stroke, psyche, arthre
    FROM source_base
    UNPIVOT INCLUDE NULLS
    (
        (shlt, bmi, hibpe, diabe, cancre, lunge, hearte, stroke, psyche, arthre) FOR wave_number IN
        (
        (R1SHLT, R1BMI, R1HIBPE, R1DIABE, R1CANCRE, R1LUNGE, R1HEARTE, R1STROKE, R1PSYCHE, R1ARTHRE) AS `1`,
        (R2SHLT, R2BMI, R2HIBPE, R2DIABE, R2CANCRE, R2LUNGE, R2HEARTE, R2STROKE, R2PSYCHE, R2ARTHRE) AS `2`,
        (R3SHLT, R3BMI, R3HIBPE, R3DIABE, R3CANCRE, R3LUNGE, R3HEARTE, R3STROKE, R3PSYCHE, R3ARTHRE) AS `3`,
        (R4SHLT, R4BMI, R4HIBPE, R4DIABE, R4CANCRE, R4LUNGE, R4HEARTE, R4STROKE, R4PSYCHE, R4ARTHRE) AS `4`,
        (R5SHLT, R5BMI, R5HIBPE, R5DIABE, R5CANCRE, R5LUNGE, R5HEARTE, R5STROKE, R5PSYCHE, R5ARTHRE) AS `5`,
        (R6SHLT, R6BMI, R6HIBPE, R6DIABE, R6CANCRE, R6LUNGE, R6HEARTE, R6STROKE, R6PSYCHE, R6ARTHRE) AS `6`,
        (R7SHLT, R7BMI, R7HIBPE, R7DIABE, R7CANCRE, R7LUNGE, R7HEARTE, R7STROKE, R7PSYCHE, R7ARTHRE) AS `7`,
        (R8SHLT, R8BMI, R8HIBPE, R8DIABE, R8CANCRE, R8LUNGE, R8HEARTE, R8STROKE, R8PSYCHE, R8ARTHRE) AS `8`,
        (R9SHLT, R9BMI, R9HIBPE, R9DIABE, R9CANCRE, R9LUNGE, R9HEARTE, R9STROKE, R9PSYCHE, R9ARTHRE) AS `9`,
        (R10SHLT, R10BMI, R10HIBPE, R10DIABE, R10CANCRE, R10LUNGE, R10HEARTE, R10STROKE, R10PSYCHE, R10ARTHRE) AS `10`,
        (R11SHLT, R11BMI, R11HIBPE, R11DIABE, R11CANCRE, R11LUNGE, R11HEARTE, R11STROKE, R11PSYCHE, R11ARTHRE) AS `11`,
        (R12SHLT, R12BMI, R12HIBPE, R12DIABE, R12CANCRE, R12LUNGE, R12HEARTE, R12STROKE, R12PSYCHE, R12ARTHRE) AS `12`,
        (R13SHLT, R13BMI, R13HIBPE, R13DIABE, R13CANCRE, R13LUNGE, R13HEARTE, R13STROKE, R13PSYCHE, R13ARTHRE) AS `13`,
        (R14SHLT, R14BMI, R14HIBPE, R14DIABE, R14CANCRE, R14LUNGE, R14HEARTE, R14STROKE, R14PSYCHE, R14ARTHRE) AS `14`,
        (R15SHLT, R15BMI, R15HIBPE, R15DIABE, R15CANCRE, R15LUNGE, R15HEARTE, R15STROKE, R15PSYCHE, R15ARTHRE) AS `15`,
        (R16SHLT, R16BMI, R16HIBPE, R16DIABE, R16CANCRE, R16LUNGE, R16HEARTE, R16STROKE, R16PSYCHE, R16ARTHRE) AS `16`
        )
    )
),
resolved_observations AS
(
    SELECT r.respondent_id,
        w.wave_id,
        TRY_CAST(shlt AS TINYINT) AS shlt,
        TRY_CAST(bmi AS DOUBLE) AS bmi,
        TRY_CAST(hibpe AS TINYINT) AS hibpe,
        TRY_CAST(diabe AS TINYINT) AS diabe,
        TRY_CAST(cancre AS TINYINT) AS cancre,
        TRY_CAST(lunge AS TINYINT) AS lunge,
        TRY_CAST(hearte AS TINYINT) AS hearte,
        TRY_CAST(stroke AS TINYINT) AS stroke,
        TRY_CAST(psyche AS TINYINT) AS psyche,
        TRY_CAST(arthre AS TINYINT) AS arthre
    FROM wave_observations o
    LEFT JOIN dev_catalog.slv_cdm_hrs.codex_hub_respondent r
        ON o.HHIDPN = r.hhidpn
    LEFT JOIN dev_catalog.slv_cdm_hrs.codex_dim_wave w
        ON o.wave_number = w.wave_number
),
deduplicated_observations AS
(
    SELECT DISTINCT *
    FROM resolved_observations
),
unique_business_keys AS
(
    SELECT respondent_id,
        wave_id
    FROM deduplicated_observations
    WHERE respondent_id IS NOT NULL AND wave_id IS NOT NULL
    GROUP BY respondent_id, wave_id
    HAVING COUNT(*) = 1
)
SELECT respondent_id,
    wave_id
FROM resolved_observations
WHERE respondent_id IS NULL OR wave_id IS NULL;

WITH source_base AS
(
    SELECT HHIDPN,
        R1SHLT,
        R1BMI,
        R1HIBPE,
        R1DIABE,
        R1CANCRE,
        R1LUNGE,
        R1HEARTE,
        R1STROKE,
        R1PSYCHE,
        R1ARTHRE,
        R2SHLT,
        R2BMI,
        R2HIBPE,
        R2DIABE,
        R2CANCRE,
        R2LUNGE,
        R2HEARTE,
        R2STROKE,
        R2PSYCHE,
        R2ARTHRE,
        R3SHLT,
        R3BMI,
        R3HIBPE,
        R3DIABE,
        R3CANCRE,
        R3LUNGE,
        R3HEARTE,
        R3STROKE,
        R3PSYCHE,
        R3ARTHRE,
        R4SHLT,
        R4BMI,
        R4HIBPE,
        R4DIABE,
        R4CANCRE,
        R4LUNGE,
        R4HEARTE,
        R4STROKE,
        R4PSYCHE,
        R4ARTHRE,
        R5SHLT,
        R5BMI,
        R5HIBPE,
        R5DIABE,
        R5CANCRE,
        R5LUNGE,
        R5HEARTE,
        R5STROKE,
        R5PSYCHE,
        R5ARTHRE,
        R6SHLT,
        R6BMI,
        R6HIBPE,
        R6DIABE,
        R6CANCRE,
        R6LUNGE,
        R6HEARTE,
        R6STROKE,
        R6PSYCHE,
        R6ARTHRE,
        R7SHLT,
        R7BMI,
        R7HIBPE,
        R7DIABE,
        R7CANCRE,
        R7LUNGE,
        R7HEARTE,
        R7STROKE,
        R7PSYCHE,
        R7ARTHRE,
        R8SHLT,
        R8BMI,
        R8HIBPE,
        R8DIABE,
        R8CANCRE,
        R8LUNGE,
        R8HEARTE,
        R8STROKE,
        R8PSYCHE,
        R8ARTHRE,
        R9SHLT,
        R9BMI,
        R9HIBPE,
        R9DIABE,
        R9CANCRE,
        R9LUNGE,
        R9HEARTE,
        R9STROKE,
        R9PSYCHE,
        R9ARTHRE,
        R10SHLT,
        R10BMI,
        R10HIBPE,
        R10DIABE,
        R10CANCRE,
        R10LUNGE,
        R10HEARTE,
        R10STROKE,
        R10PSYCHE,
        R10ARTHRE,
        R11SHLT,
        R11BMI,
        R11HIBPE,
        R11DIABE,
        R11CANCRE,
        R11LUNGE,
        R11HEARTE,
        R11STROKE,
        R11PSYCHE,
        R11ARTHRE,
        R12SHLT,
        R12BMI,
        R12HIBPE,
        R12DIABE,
        R12CANCRE,
        R12LUNGE,
        R12HEARTE,
        R12STROKE,
        R12PSYCHE,
        R12ARTHRE,
        R13SHLT,
        R13BMI,
        R13HIBPE,
        R13DIABE,
        R13CANCRE,
        R13LUNGE,
        R13HEARTE,
        R13STROKE,
        R13PSYCHE,
        R13ARTHRE,
        R14SHLT,
        R14BMI,
        R14HIBPE,
        R14DIABE,
        R14CANCRE,
        R14LUNGE,
        R14HEARTE,
        R14STROKE,
        R14PSYCHE,
        R14ARTHRE,
        R15SHLT,
        R15BMI,
        R15HIBPE,
        R15DIABE,
        R15CANCRE,
        R15LUNGE,
        R15HEARTE,
        R15STROKE,
        R15PSYCHE,
        R15ARTHRE,
        R16SHLT,
        R16BMI,
        R16HIBPE,
        R16DIABE,
        R16CANCRE,
        R16LUNGE,
        R16HEARTE,
        R16STROKE,
        R16PSYCHE,
        R16ARTHRE
    FROM dev_catalog.brz_raw_hrs.randhrs1992_2022v1
),
wave_observations AS
(
    SELECT HHIDPN,
        wave_number,
        shlt, bmi, hibpe, diabe, cancre, lunge, hearte, stroke, psyche, arthre
    FROM source_base
    UNPIVOT INCLUDE NULLS
    (
        (shlt, bmi, hibpe, diabe, cancre, lunge, hearte, stroke, psyche, arthre) FOR wave_number IN
        (
        (R1SHLT, R1BMI, R1HIBPE, R1DIABE, R1CANCRE, R1LUNGE, R1HEARTE, R1STROKE, R1PSYCHE, R1ARTHRE) AS `1`,
        (R2SHLT, R2BMI, R2HIBPE, R2DIABE, R2CANCRE, R2LUNGE, R2HEARTE, R2STROKE, R2PSYCHE, R2ARTHRE) AS `2`,
        (R3SHLT, R3BMI, R3HIBPE, R3DIABE, R3CANCRE, R3LUNGE, R3HEARTE, R3STROKE, R3PSYCHE, R3ARTHRE) AS `3`,
        (R4SHLT, R4BMI, R4HIBPE, R4DIABE, R4CANCRE, R4LUNGE, R4HEARTE, R4STROKE, R4PSYCHE, R4ARTHRE) AS `4`,
        (R5SHLT, R5BMI, R5HIBPE, R5DIABE, R5CANCRE, R5LUNGE, R5HEARTE, R5STROKE, R5PSYCHE, R5ARTHRE) AS `5`,
        (R6SHLT, R6BMI, R6HIBPE, R6DIABE, R6CANCRE, R6LUNGE, R6HEARTE, R6STROKE, R6PSYCHE, R6ARTHRE) AS `6`,
        (R7SHLT, R7BMI, R7HIBPE, R7DIABE, R7CANCRE, R7LUNGE, R7HEARTE, R7STROKE, R7PSYCHE, R7ARTHRE) AS `7`,
        (R8SHLT, R8BMI, R8HIBPE, R8DIABE, R8CANCRE, R8LUNGE, R8HEARTE, R8STROKE, R8PSYCHE, R8ARTHRE) AS `8`,
        (R9SHLT, R9BMI, R9HIBPE, R9DIABE, R9CANCRE, R9LUNGE, R9HEARTE, R9STROKE, R9PSYCHE, R9ARTHRE) AS `9`,
        (R10SHLT, R10BMI, R10HIBPE, R10DIABE, R10CANCRE, R10LUNGE, R10HEARTE, R10STROKE, R10PSYCHE, R10ARTHRE) AS `10`,
        (R11SHLT, R11BMI, R11HIBPE, R11DIABE, R11CANCRE, R11LUNGE, R11HEARTE, R11STROKE, R11PSYCHE, R11ARTHRE) AS `11`,
        (R12SHLT, R12BMI, R12HIBPE, R12DIABE, R12CANCRE, R12LUNGE, R12HEARTE, R12STROKE, R12PSYCHE, R12ARTHRE) AS `12`,
        (R13SHLT, R13BMI, R13HIBPE, R13DIABE, R13CANCRE, R13LUNGE, R13HEARTE, R13STROKE, R13PSYCHE, R13ARTHRE) AS `13`,
        (R14SHLT, R14BMI, R14HIBPE, R14DIABE, R14CANCRE, R14LUNGE, R14HEARTE, R14STROKE, R14PSYCHE, R14ARTHRE) AS `14`,
        (R15SHLT, R15BMI, R15HIBPE, R15DIABE, R15CANCRE, R15LUNGE, R15HEARTE, R15STROKE, R15PSYCHE, R15ARTHRE) AS `15`,
        (R16SHLT, R16BMI, R16HIBPE, R16DIABE, R16CANCRE, R16LUNGE, R16HEARTE, R16STROKE, R16PSYCHE, R16ARTHRE) AS `16`
        )
    )
),
resolved_observations AS
(
    SELECT r.respondent_id,
        w.wave_id,
        TRY_CAST(shlt AS TINYINT) AS shlt,
        TRY_CAST(bmi AS DOUBLE) AS bmi,
        TRY_CAST(hibpe AS TINYINT) AS hibpe,
        TRY_CAST(diabe AS TINYINT) AS diabe,
        TRY_CAST(cancre AS TINYINT) AS cancre,
        TRY_CAST(lunge AS TINYINT) AS lunge,
        TRY_CAST(hearte AS TINYINT) AS hearte,
        TRY_CAST(stroke AS TINYINT) AS stroke,
        TRY_CAST(psyche AS TINYINT) AS psyche,
        TRY_CAST(arthre AS TINYINT) AS arthre
    FROM wave_observations o
    LEFT JOIN dev_catalog.slv_cdm_hrs.codex_hub_respondent r
        ON o.HHIDPN = r.hhidpn
    LEFT JOIN dev_catalog.slv_cdm_hrs.codex_dim_wave w
        ON o.wave_number = w.wave_number
),
deduplicated_observations AS
(
    SELECT DISTINCT *
    FROM resolved_observations
),
unique_business_keys AS
(
    SELECT respondent_id,
        wave_id
    FROM deduplicated_observations
    WHERE respondent_id IS NOT NULL AND wave_id IS NOT NULL
    GROUP BY respondent_id, wave_id
    HAVING COUNT(*) = 1
)
SELECT respondent_id,
    wave_id,
    COUNT(*) AS record_count
FROM deduplicated_observations
WHERE respondent_id IS NOT NULL AND wave_id IS NOT NULL
GROUP BY respondent_id, wave_id
HAVING COUNT(*) > 1;

WITH source_base AS
(
    SELECT HHIDPN,
        R1SHLT,
        R1BMI,
        R1HIBPE,
        R1DIABE,
        R1CANCRE,
        R1LUNGE,
        R1HEARTE,
        R1STROKE,
        R1PSYCHE,
        R1ARTHRE,
        R2SHLT,
        R2BMI,
        R2HIBPE,
        R2DIABE,
        R2CANCRE,
        R2LUNGE,
        R2HEARTE,
        R2STROKE,
        R2PSYCHE,
        R2ARTHRE,
        R3SHLT,
        R3BMI,
        R3HIBPE,
        R3DIABE,
        R3CANCRE,
        R3LUNGE,
        R3HEARTE,
        R3STROKE,
        R3PSYCHE,
        R3ARTHRE,
        R4SHLT,
        R4BMI,
        R4HIBPE,
        R4DIABE,
        R4CANCRE,
        R4LUNGE,
        R4HEARTE,
        R4STROKE,
        R4PSYCHE,
        R4ARTHRE,
        R5SHLT,
        R5BMI,
        R5HIBPE,
        R5DIABE,
        R5CANCRE,
        R5LUNGE,
        R5HEARTE,
        R5STROKE,
        R5PSYCHE,
        R5ARTHRE,
        R6SHLT,
        R6BMI,
        R6HIBPE,
        R6DIABE,
        R6CANCRE,
        R6LUNGE,
        R6HEARTE,
        R6STROKE,
        R6PSYCHE,
        R6ARTHRE,
        R7SHLT,
        R7BMI,
        R7HIBPE,
        R7DIABE,
        R7CANCRE,
        R7LUNGE,
        R7HEARTE,
        R7STROKE,
        R7PSYCHE,
        R7ARTHRE,
        R8SHLT,
        R8BMI,
        R8HIBPE,
        R8DIABE,
        R8CANCRE,
        R8LUNGE,
        R8HEARTE,
        R8STROKE,
        R8PSYCHE,
        R8ARTHRE,
        R9SHLT,
        R9BMI,
        R9HIBPE,
        R9DIABE,
        R9CANCRE,
        R9LUNGE,
        R9HEARTE,
        R9STROKE,
        R9PSYCHE,
        R9ARTHRE,
        R10SHLT,
        R10BMI,
        R10HIBPE,
        R10DIABE,
        R10CANCRE,
        R10LUNGE,
        R10HEARTE,
        R10STROKE,
        R10PSYCHE,
        R10ARTHRE,
        R11SHLT,
        R11BMI,
        R11HIBPE,
        R11DIABE,
        R11CANCRE,
        R11LUNGE,
        R11HEARTE,
        R11STROKE,
        R11PSYCHE,
        R11ARTHRE,
        R12SHLT,
        R12BMI,
        R12HIBPE,
        R12DIABE,
        R12CANCRE,
        R12LUNGE,
        R12HEARTE,
        R12STROKE,
        R12PSYCHE,
        R12ARTHRE,
        R13SHLT,
        R13BMI,
        R13HIBPE,
        R13DIABE,
        R13CANCRE,
        R13LUNGE,
        R13HEARTE,
        R13STROKE,
        R13PSYCHE,
        R13ARTHRE,
        R14SHLT,
        R14BMI,
        R14HIBPE,
        R14DIABE,
        R14CANCRE,
        R14LUNGE,
        R14HEARTE,
        R14STROKE,
        R14PSYCHE,
        R14ARTHRE,
        R15SHLT,
        R15BMI,
        R15HIBPE,
        R15DIABE,
        R15CANCRE,
        R15LUNGE,
        R15HEARTE,
        R15STROKE,
        R15PSYCHE,
        R15ARTHRE,
        R16SHLT,
        R16BMI,
        R16HIBPE,
        R16DIABE,
        R16CANCRE,
        R16LUNGE,
        R16HEARTE,
        R16STROKE,
        R16PSYCHE,
        R16ARTHRE
    FROM dev_catalog.brz_raw_hrs.randhrs1992_2022v1
),
wave_observations AS
(
    SELECT HHIDPN,
        wave_number,
        shlt, bmi, hibpe, diabe, cancre, lunge, hearte, stroke, psyche, arthre
    FROM source_base
    UNPIVOT INCLUDE NULLS
    (
        (shlt, bmi, hibpe, diabe, cancre, lunge, hearte, stroke, psyche, arthre) FOR wave_number IN
        (
        (R1SHLT, R1BMI, R1HIBPE, R1DIABE, R1CANCRE, R1LUNGE, R1HEARTE, R1STROKE, R1PSYCHE, R1ARTHRE) AS `1`,
        (R2SHLT, R2BMI, R2HIBPE, R2DIABE, R2CANCRE, R2LUNGE, R2HEARTE, R2STROKE, R2PSYCHE, R2ARTHRE) AS `2`,
        (R3SHLT, R3BMI, R3HIBPE, R3DIABE, R3CANCRE, R3LUNGE, R3HEARTE, R3STROKE, R3PSYCHE, R3ARTHRE) AS `3`,
        (R4SHLT, R4BMI, R4HIBPE, R4DIABE, R4CANCRE, R4LUNGE, R4HEARTE, R4STROKE, R4PSYCHE, R4ARTHRE) AS `4`,
        (R5SHLT, R5BMI, R5HIBPE, R5DIABE, R5CANCRE, R5LUNGE, R5HEARTE, R5STROKE, R5PSYCHE, R5ARTHRE) AS `5`,
        (R6SHLT, R6BMI, R6HIBPE, R6DIABE, R6CANCRE, R6LUNGE, R6HEARTE, R6STROKE, R6PSYCHE, R6ARTHRE) AS `6`,
        (R7SHLT, R7BMI, R7HIBPE, R7DIABE, R7CANCRE, R7LUNGE, R7HEARTE, R7STROKE, R7PSYCHE, R7ARTHRE) AS `7`,
        (R8SHLT, R8BMI, R8HIBPE, R8DIABE, R8CANCRE, R8LUNGE, R8HEARTE, R8STROKE, R8PSYCHE, R8ARTHRE) AS `8`,
        (R9SHLT, R9BMI, R9HIBPE, R9DIABE, R9CANCRE, R9LUNGE, R9HEARTE, R9STROKE, R9PSYCHE, R9ARTHRE) AS `9`,
        (R10SHLT, R10BMI, R10HIBPE, R10DIABE, R10CANCRE, R10LUNGE, R10HEARTE, R10STROKE, R10PSYCHE, R10ARTHRE) AS `10`,
        (R11SHLT, R11BMI, R11HIBPE, R11DIABE, R11CANCRE, R11LUNGE, R11HEARTE, R11STROKE, R11PSYCHE, R11ARTHRE) AS `11`,
        (R12SHLT, R12BMI, R12HIBPE, R12DIABE, R12CANCRE, R12LUNGE, R12HEARTE, R12STROKE, R12PSYCHE, R12ARTHRE) AS `12`,
        (R13SHLT, R13BMI, R13HIBPE, R13DIABE, R13CANCRE, R13LUNGE, R13HEARTE, R13STROKE, R13PSYCHE, R13ARTHRE) AS `13`,
        (R14SHLT, R14BMI, R14HIBPE, R14DIABE, R14CANCRE, R14LUNGE, R14HEARTE, R14STROKE, R14PSYCHE, R14ARTHRE) AS `14`,
        (R15SHLT, R15BMI, R15HIBPE, R15DIABE, R15CANCRE, R15LUNGE, R15HEARTE, R15STROKE, R15PSYCHE, R15ARTHRE) AS `15`,
        (R16SHLT, R16BMI, R16HIBPE, R16DIABE, R16CANCRE, R16LUNGE, R16HEARTE, R16STROKE, R16PSYCHE, R16ARTHRE) AS `16`
        )
    )
),
resolved_observations AS
(
    SELECT r.respondent_id,
        w.wave_id,
        TRY_CAST(shlt AS TINYINT) AS shlt,
        TRY_CAST(bmi AS DOUBLE) AS bmi,
        TRY_CAST(hibpe AS TINYINT) AS hibpe,
        TRY_CAST(diabe AS TINYINT) AS diabe,
        TRY_CAST(cancre AS TINYINT) AS cancre,
        TRY_CAST(lunge AS TINYINT) AS lunge,
        TRY_CAST(hearte AS TINYINT) AS hearte,
        TRY_CAST(stroke AS TINYINT) AS stroke,
        TRY_CAST(psyche AS TINYINT) AS psyche,
        TRY_CAST(arthre AS TINYINT) AS arthre
    FROM wave_observations o
    LEFT JOIN dev_catalog.slv_cdm_hrs.codex_hub_respondent r
        ON o.HHIDPN = r.hhidpn
    LEFT JOIN dev_catalog.slv_cdm_hrs.codex_dim_wave w
        ON o.wave_number = w.wave_number
),
deduplicated_observations AS
(
    SELECT DISTINCT *
    FROM resolved_observations
),
unique_business_keys AS
(
    SELECT respondent_id,
        wave_id
    FROM deduplicated_observations
    WHERE respondent_id IS NOT NULL AND wave_id IS NOT NULL
    GROUP BY respondent_id, wave_id
    HAVING COUNT(*) = 1
)
INSERT INTO dev_catalog.slv_cdm_hrs.codex_fact_health
(
    respondent_id,
    wave_id,
    shlt,
    bmi,
    hibpe,
    diabe,
    cancre,
    lunge,
    hearte,
    stroke,
    psyche,
    arthre,
    create_date,
    update_date,
    active
)
SELECT s.respondent_id,
    s.wave_id,
    s.shlt,
    s.bmi,
    s.hibpe,
    s.diabe,
    s.cancre,
    s.lunge,
    s.hearte,
    s.stroke,
    s.psyche,
    s.arthre,
    CURRENT_DATE() AS create_date,
    CURRENT_DATE() AS update_date,
    TRUE AS active
FROM deduplicated_observations s
JOIN unique_business_keys k
    ON s.respondent_id = k.respondent_id
    AND s.wave_id = k.wave_id
WHERE NOT EXISTS
    (
        SELECT 1
        FROM dev_catalog.slv_cdm_hrs.codex_fact_health t
        WHERE t.respondent_id = s.respondent_id
            AND t.wave_id = s.wave_id
    );
