DROP TABLE IF EXISTS IDENTIFIER(
    CONCAT(
        :catalog_name,
        '.',
        :schema_prefix,
        '.dim_hrs_wave'
    )
);
CREATE TABLE IDENTIFIER(
    CONCAT(
        :catalog_name,
        '.',
        :schema_prefix,
        '.dim_hrs_wave'
    )
) (
    wave_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    wave_number STRING,
    wave_year STRING,
    wave_description STRING,
    create_date DATE,
    update_date DATE,
    active BOOLEAN
) USING DELTA COMMENT 'Wave tracking table';