DROP TABLE IF EXISTS dev_catalog.gld_star_hrs.dim_hrs_wave;
CREATE TABLE dev_catalog.gld_star_hrs.dim_hrs_wave (
    wave_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    wave_number STRING,
    wave_year STRING,
    wave_description STRING,
    create_date DATE,
    update_date DATE,
    active BOOLEAN
) USING DELTA COMMENT 'Wave tracking table';