DROP TABLE IF EXISTS dev_catalog.gld_star_hrs.dim_hrs_cohort;
CREATE TABLE dev_catalog.gld_star_hrs.dim_hrs_cohort (
    cohort_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    hacohort_number INT,
    hacohort_label STRING,
    hacohort_description STRING,
    create_date DATE,
    update_date DATE,
    active BOOLEAN
) USING DELTA COMMENT 'Cohort tracking table';