# ==========================================================
# Continuous Deployment
#
# Purpose:
#   Deploy the Databricks Asset Bundle and execute the
#   HRS ETL workflow.
#
# Deployment Flow
#
# Checkout Repository
#        │
#        ▼
# Install Databricks CLI
#        │
#        ▼
# Test Databricks Connection
#        │
#        ▼
# Deploy Asset Bundle
#        │
#        ▼
# Execute HRS Workflow
#        │
#        ▼
# Deployment Summary
#
# ==========================================================

name: Continuous Deployment

on:
  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      #---------------------------------------
      # Checkout Repository
      #---------------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4

      #---------------------------------------
      # Install Databricks CLI
      #---------------------------------------
      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      #---------------------------------------
      # Verify CLI
      #---------------------------------------
      - name: Verify Databricks CLI
        run: databricks version

      #---------------------------------------
      # Test Workspace Connection
      #---------------------------------------
      - name: Test Databricks Connection
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

        run: |
          databricks current-user me

      #---------------------------------------
      # Deploy Bundle
      #---------------------------------------
      - name: Deploy Asset Bundle
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

        run: |
          databricks bundle deploy

      #---------------------------------------
      # Execute Workflow
      #---------------------------------------
      - name: Run HRS ETL Workflow

        timeout-minutes: 30                    # This prevents a GitHub runner from waiting indefinitely if a Databricks job hangs.

        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

        run: |
          databricks bundle run hrs_etl_job

      #---------------------------------------
      # Summary
      #---------------------------------------
      - name: Deployment Summary
        run: |
          echo "======================================"
          echo "Deployment completed successfully"
          echo "Bundle deployed"
          echo "HRS workflow executed"
          echo "======================================"